version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - users-service
      - posts-service
    environment:
      - ENVIRONMENT=development

 # Databases
  users-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - users_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  posts-db:
    image: postgres:15
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - posts_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d posts_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  comments-db:
    image: postgres:15
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - comments_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d comments_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9092,CONTROLLER://:29093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

# Microservices
  users-service:
    build: ./users-service
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_HOST=users-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=users_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      users-db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure:5
  
  posts-service:
    build: ./posts-service
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_HOST=posts-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=posts_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      posts-db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure:5
  
  comments-service:
    build: ./comments-service
    ports:
      - "8003:8003"
    environment:
      - POSTGRES_HOST=comments-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=comments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      comments-db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure:5

volumes:
  users_db_data:
  posts_db_data:
  comments_db_data: